title:            moguangquan-blog
description:      welcome to my blog.The blog is still biulding
reading_time:     true
words_per_minute: 30
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://moguangquan.github.io/blog

disqus_shortname:  moguangquan    #disqus插件的简称
uyan_shortname:        #uyan插件的简称
duoshuo_shortname:     #duoshuo插件的简称

# Owner/author information
owner:
  name:           moguangquan
  avatar:         avatar.jpg
  bio:            "i am a chinese software engineer man.now work on guangzhou."
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:         moguangquan
  stackexchange:
  linkedin:       ../profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
markdown:    kramdown
gems: [jekyll-paginate, jekyll-gist]
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3

kramdown:
  input: GFM
  syntax_highlighter: rouge

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
